import pygame as pg
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ecs import Entity

class GameState:
    is_pausable = False
    entities: list['Entity'] = []
    def enter(self):...
    def exit(self):...
    def handle_event(self, event):...
    def update(self, dt):...
    def render(self, screen):...